name: portfolio-production

services:
    website:
        container_name: portfolio-website-production

        build:
            context: .

            dockerfile: Dockerfile

            target: production

        environment:
            - HOSTNAME=${HOSTNAME}
            - PORT=${PORT}

        ports:
            - ${PORT}:3000

        restart: always
